#!/bin/bash

#  Colors
magenta=$'\e[0;1;95;40m'
reset=$'\e[0m'

#mkdir -p ~/scripts
#mv x_* ~/scripts/
#mv .git ~/scripts/
#mv README.md ~/scripts/
#mv update_scripts ~/scripts/
#rm install
echo -e "Finished. You ${magenta}might${reset} have to ${magenta}delete the folder${reset}."
