#!/bin/bash

#  Colors
green=$'\e[0;92;40m'
green_b=$'\e[0;30;102m'
green_d=$'\e[0;2;92;40m'
blue=$'\e[0;34;40m'
cyan=$'\e[0;1;36;40m'
magenta=$'\e[0;1;95;40m'
reset=$'\e[0m'

while [ "$input" != "n" ] && [ "$input" != "y" ] && [ "$input" != "N" ] && [ "$input" != "Y" ]
		do
read -n1 -p "${green}Do you want to update ${cyan}scripts${green}?${green_d} This will overwrite any changes / differences with the repo ${magenta}(y/n)${blue} " input
			echo "${reset}"
		done
	if [ "$input" = "y" ] || [ "$input" = "Y" ]
		then
		echo "${green}Updating...${reset}"
		git fetch --all
		git reset --hard origin/master
		rm install
		echo -e "${green_b}Finished.${reset} Scripts are up to date."
	fi
