#!/bin/bash

b=$'\e[1;91m'
rs=$'\e[0m'

spinner=(" |${b}'${rs}       | " " |${b} '${rs}      | " " |${b} .${rs}      | " " |${b}  '${rs}     | " " |  ${b} .${rs}    | " " | ${b}   '${rs}   | " " |   ${b}  .${rs}  | " " |   ${b}   '${rs}  |" " |   ${b}    .${rs} |" " |   ${b}    '${rs}| " " |     ${b} '${rs} | " " |   ${b}  .${rs}  | " " |  ${b}  '${rs}   | " " | ${b}  . ${rs}   | " " | ${b} ' ${rs}    | " "|${b}  .${rs}      | " "|${b} ' ${rs}      | ")

function other(){
	cycle &
	pid=$!

	bash $1
	
	kill $pid
	echo -e "${rs} "
}

function test(){
	cycle &
	pid=$!

	echo "Hello"
	sleep "$1"

	kill $pid
	echo -e "${rs} "
}

function cycle() {
	while [ 1 ]
	do
		for i in "${spinner[@]}"
		do
			echo -ne "\r$i"
			sleep 0.13
		done
	done
}

#test 6
#cycle
other "$1"
