#!/bin/bash

function watch() {
while :; do clear; your_command; sleep 2; done
}

function cycle() {
 t=0
 t2=$1
 str="Please wait: "
 p=0
 cps=$(($2-1))
 while [ $t2 -gt 0 ]
	 do
		 echo -ne "\r\033[K${str}${t2} seconds   "
		if [ $t -eq 0 ]
			then
			echo -ne " |"
		fi

		if [ $t -eq 1 ]
			then
			echo -ne " /"
		fi

		if [ $t -eq 2 ]
			then
			echo -ne " -"
		fi

		if [ $t -eq 3 ]
			then
			echo -ne " \\"
		fi

		(( t++ ))

		if [ $t -ge 4 ]
			then
			t=0
		fi

		if [ $p -lt $cps ]
		then
			(( p++ ))
		else
			(( t2-- ))
			p=0
		fi
		sleep $(echo "scale=3; (1/($cps+1))" | bc)

	done
}
cycle "10" "6"
